services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin

    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris

    ports:
      - "8096:8096"

    devices:
      - /dev/dri:/dev/dri
      
    volumes:
      - /volume1/homelab/appdata/jellyfin:/config
      - /volume1/homelab/media/tv:/data/tvshows
      - /volume1/homelab/media/movies:/data/movies

    networks:
      - homelab

networks:
  homelab:
    external: true
