services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    
    networks:
      - homelab 

    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - "9696:9696"

    volumes:
      - /volume1/homelab/appdata/prowlarr:/config

networks:
  homelab:
    external: true
