services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    env_file:
      - .env

    ports:
      - "8080:8080"
      - "6881:6881/tcp"
      - "6881:6881/udp"

    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent

    network_mode: "service:gluetun"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881

    volumes:
      - /volume1/homelab/appdata/qbittorrent:/config
      - /volume1/homelab/downloads:/downloads

    restart: unless-stopped
